name: super_app_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sub_app_core:
    git: https://github.com/devnoaman/sub_app_core.git
  api_client:
    git: https://github.com/devnoaman/api_client.git

  shared:
    path: ../../packages/shared
  super_app_manager:
    path: ../../packages/super_app_manager

  flutter_inappwebview: ^6.1.5
  image_picker: ^1.2.0
  flutter_popup: ^3.3.9
  wakelock_plus: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  watcher: ^1.1.4
dependency_overrides: 
  package_info_plus: ^8.0.0

flutter:
  uses-material-design: true
